### ISSUE TITLE
torrc question

### ISSUE THREAD

**Issue by vanguard71** [Juniorn1003/Faitagram#23]
Justin,
   I am running a non kali linux distribution.   Can you please confirm the following:

1.   Which line were you un-commenting in setup.py\\
#SOCKSPort 9050 ?

2.  In main script, is it also trying to read the same above line?

    with open('/etc/tor/torrc','r') as f:

        contents = f.readlines()

        data = contents[59]

        Hash = data.rsplit(":",1)[1]

**Comment by Juniorn1003** [comment]
Oh, there are three lines that has to be uncommented in torrc. the cookie authentication, control port 9050 and hashedpassword. The setup.py uncomments them, and in the main script the script reads the hashed control password. Since that is the way to connect to tor. But I did not decide yet to delete this line or not since the proxy problem was way too in the way, and this method was not working well.

**Comment by Juniorn1003** [comment]
I will close this now, if you want to ask more then go to the "Questions!" issue.
