### ISSUE TITLE
script suggestion

### ISSUE THREAD

**Issue by vanguard71** [Juniorn1003/Faitagram#25]
Justin,
   Thank you again for making this script working.   I have some suggestion, please let me know if they make sense

1.  User check function unnecessary:   There is no correlation between trying different password and usercheck method.   At the beginning of script, I can just proceed by typing any common name like "David" and script will let us proceed.   I think this is unnecessary as private profile will always fail during script execution and exit script

2.  checking current ip address.   currently you are checking ip address by 

my_ip = urlopen("http://ip.42.pl/raw").read()

The above will always give your real ip address, not what tor changing it to.  

3.   Also, since, you are using tor to change ip address, why not use tor browser itself.   When you are using firefox, it maybe loosing its effect.  

Better yet, why not remove some of the heavier things from the script and make it bare bone script.

Use 
a. tor to change ip
b. use curl to send requst
c. perform xml parsing to verify whether we are successful; thus remove dependency on heavier things like selenium.   Anytime I see JAVA dependency, it tells me, soon or later there will be memory bloating.

Please let me know if they make sense, I can possibly lend a hand in this with my limited knowledge of http protocol.

**Comment by Juniorn1003** [comment]
Hmm... Thanks! Will look forward to this. But, I there is a another section to suggest, it is called "Pull requests."

**Comment by Juniorn1003** [comment]
But 1. Usercheck is to differentiate different usernames, because you also need to enter the username of the account. 2, Security uses that, so I will need to use that. To get not get caught, I would have to change the "view" of the public IP. Even a simple website like ip.42.pl can see your public IP, how can major internet sites like facebook, instagram and twitter not have those securities? and b, using curl to send request, a dude called "Ethical-H4CK3R" Used that method, but the script kept failing.
